<a href="https://colab.research.google.com/github/Sirigalla34/deep-learning-programs/blob/main/gru_forward_pass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.set_printoptions(suppress=True)
def sigmoid(x):
 return 1/(1+np.exp(-x))
def softmax(x):
 exp_x=np.exp(x-np.max(x))
 return exp_x/np.sum(exp_x)
def cross_entropy(y_true,y_pred):
 return -np.sum(y_true*np.log(y_pred+1e-12))
def init_gate():
 return np.random.randn(hidden_size,input_size+hidden_size)*0.5
input_size=3
hidden_size=2
output_size=3
Wz=init_gate()
Wr=init_gate()
Wh=init_gate()
bz=np.zeros((hidden_size,1))
br=np.zeros((hidden_size,1))
bh=np.zeros((hidden_size,1))
Why=np.random.randn(output_size,hidden_size)*0.5
by=np.zeros((output_size,1))
x1=np.array([[1],[0],[0]])
x2=np.array([[0],[1],[0]])
x3=np.array([[0],[0],[1]])
inputs=[x1,x2,x3]
t1=np.array([[0],[1],[0]])
t2=np.array([[0],[0],[1]])
t3=np.array([[1],[0],[0]])
targets=[t1,t2,t3]
length=len(inputs)
h=np.zeros((hidden_size,1))
loss=0
print("Predictions:")
for t in range(length):
 z_input=np.vstack((h,inputs[t]))
 z=sigmoid(Wz@z_input+bz)
 r=sigmoid(Wr@z_input+br)
 h_input=np.vstack((r*h,inputs[t]))
 h_tilde=np.tanh(Wh@h_input+bh)
 h=(1-z)*h+z*h_tilde
 y=Why@h+by
 p=softmax(y)
 loss+=cross_entropy(targets[t],p)
 print("Time step",t+1,"prediction:")
 print(np.round(p,4))

print("Final loss:",round(loss,6))

Predictions:
Time step 1 prediction:
[[0.3797]
 [0.2411]
 [0.3792]]
Time step 2 prediction:
[[0.3496]
 [0.2692]
 [0.3811]]
Time step 3 prediction:
[[0.3082]
 [0.3396]
 [0.3522]]
Final loss: 3.564133
