<a href="https://colab.research.google.com/github/Sirigalla34/deep-learning-programs/blob/main/lstm_forward_pass_with_fixed_weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# LSTM Forward Pass with Fixed Weights
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))
def softmax(x):
    exp_x=np.exp(x-np.max(x))
    return exp_x/np.sum(exp_x)
def cross_entropy(y_true,y_pred):
    return -np.sum(y_true*np.log(y_pred+1e-12))
x1=np.array([[1],[0],[0]])
x2=np.array([[0],[1],[0]])
x3=np.array([[0],[0],[1]])
inputs=[x1,x2,x3]
t1=np.array([[0],[1],[0]])
t2=np.array([[0],[0],[1]])
t3=np.array([[1],[0],[0]])
targets=[t1,t2,t3]
hidden_size=2
h=np.zeros((hidden_size,1))
c=np.zeros((hidden_size,1))
wf=np.array([[-0.3922,-0.0009,-0.0711,-0.654,0.2],[0.7823,0.0040,0.1089,0.5633,-0.1]])
bf=np.array([[-0.7044],[0.5538]])
wi=np.array([[0.2833,-0.1896,0.7952,0.9753,0.1],[-0.0209,-0.5395,0.0708,0.3999,-0.2]])
bi=np.array([[1.594],[1.487]])
wo=np.array([[0.1023,-0.1504,1.0928,0.7877,0.3],[0.1616,-0.7025,0.187,0.9171,-0.1]])
bo=np.array([[1.8517],[1.6679]])
wc=np.array([[-1.5543,3.5032,1.0,0.0,0.2],[3.7474,-0.413,0.0,1.0,-0.3]])
bc=np.array([[0.3001],[0.4305]])
why=np.array([[-1.5543,3.5032],[3.7474,-0.413],[-2.6135,-2.9926]])
by=np.array([[0.3001],[0.4305],[-0.7804]])
loss=0
print("Predictions:\n")
for t in range(3):
    z=np.vstack((h,inputs[t]))
    f=sigmoid(wf@z+bf)
    i=sigmoid(wi@z+bi)
    o=sigmoid(wo@z+bo)
    c_tilde=np.tanh(wc@z+bc)
    c=f*c+i*c_tilde
    h=o*np.tanh(c)
    y=why@h+by
    p=softmax(y)
    loss+=cross_entropy(targets[t],p)
    print("Time Step",t+1)
    print(np.round(p,4))
print("\nTotal Loss:",round(loss,6))

Predictions:

Time Step 1
[[0.0868]
 [0.9107]
 [0.0025]]
Time Step 2
[[0.7034]
 [0.2953]
 [0.0013]]
Time Step 3
[[2.513e-01]
 [7.482e-01]
 [6.000e-04]]

Total Loss: 8.150614
